apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plant-disease
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: plant-disease-tls
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          {{- range (index .Values.ingress.rules 0).paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
---
{{ if .Values.ingress.tlsEmail }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{ .Values.ingress.tlsEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
{{ end }}
