apiVersion: v1
kind: Secret
metadata:
  name: plant-disease-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "plant-disease.fullname" . }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  {{- range $secret := .Values.backend.secrets }}
  {{ $secret.key }}: {{ default (printf "%s-PLACEHOLDER" $secret.key) (index $.Values.secretsRaw $secret.key) | quote }}
  {{- end }}
