apiVersion: v1
kind: Secret
metadata:
  name: agrilens-secrets
  namespace: agrilens
type: Opaque
stringData:
  POSTGRES_DB: "plant_disease"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "agrilens_secure_db_password"
  REDIS_URL: "redis://redis:6379/0"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  SECRET_KEY: "agrilens-production-jwt-secret-key-2026-mlops"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
